### ISSUE TITLE
Frontend repository setup 

### ISSUE THREAD

**Issue by seunbayo** [zuri-training/MyInternApp-fe-pjt-38#1]
Frontend repository setup and detailed readme documentation to guide team members

**Comment by habeebability** [comment]
Closes https://github.com/zuri-training/MyInternApp-fe-pjt-38/pull/2

**Comment by habeebability** [comment]
Closes #2

**Comment by habeebability** [comment]
please check if my pull request has been linked correctly, @seunbayo
